### ISSUE TITLE
No datafile included

### ISSUE THREAD

**Issue by Maddocent** [uashogeschoolutrecht/NSE_Analyses#48]
In order to reproduce this analysis, access to the original data source should be included (or at least described where the file lives).

**Comment by Fraukje** [comment]
Hi @Maddocent, thanks for your feedback! This data is not freely available but can be acquired by applying for it as a higher education institution at studiekeuze123.nl; this is also described in the extend wiki in this repo.

**Comment by Maddocent** [comment]
@Fraukje De Bron vermeld in de Wiki, https://scholarworks.umass.edu/items/ff6d3798-b7e6-445f-b1a2-0d7c3d504d38 is niet beschikbaar via de gegeven link. Wellicht de bron als citatie opnemen?

**Comment by Fraukje** [comment]
@Maddocent Aha! Ik zie dat de url verouderd is: ik heb deze inmiddels aangepast.
